name: Recently Published Articles
on:
  schedule:
    # Runs at 8am daily
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://thedavecarroll.com/feed.xml"
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 10
          delete_workflow_pattern: blog-post-workflow.yml
          delete_workflow_by_state_pattern: All
