name: Add Recently Published Articles to Profile
on:
  schedule:
    # Run at 8am daily
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README with latest articles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Get Site Posts and Update README
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://thedavecarroll.com/feed.xml"
      - name: Cleanup Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 14
          delete_workflow_pattern: blog-post-workflow.yml
          #delete_workflow_by_state_pattern: All
