name: Recently Published Articles
on:
  schedule:
    # Runs at 8am daily
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://thedavecarroll.com/feed.xml"
